version: "3.8"

services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: espocrm_root
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm_user
      MYSQL_PASSWORD: espocrm_pass
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - traefik-n8n_traefik_network

  espocrm:
    image: espocrm/espocrm:latest
    restart: unless-stopped
    environment:
      - ESPO_DATABASE_DRIVER=mysql
      - ESPO_DATABASE_HOST=db
      - ESPO_DATABASE_NAME=espocrm
      - ESPO_DATABASE_USER=espocrm_user
      - ESPO_DATABASE_PASSWORD=espocrm_pass
    depends_on:
      - db
    networks:
      - traefik-n8n_traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.espocrm.rule=Host(`crm.spectrumsys.pro`)"
      - "traefik.http.routers.espocrm.entrypoints=websecure"
      - "traefik.http.routers.espocrm.tls=true"
      - "traefik.http.routers.espocrm.tls.certresolver=myresolver"
      - "traefik.http.services.espocrm.loadbalancer.server.port=80"
    volumes:
      - ./espocrm_data:/var/www/html

networks:
  traefik-n8n_traefik_network:
    external: true
